language: node_js

node_js:
   - 7

branches:
  only:
    - /.*/

notifications:
    email: true

sudo: true

before_install:
    - yarn global add codecov

after_success:
    - codecov

services:
    - redis-server